[
  {
    id: "LWH7QK3NXUO30",
    name: "火花思维",
    description: "",
    children: [],
    modificationTime: 1716345402179,
    tags: ["火花思维"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWH7CQUGWHB8Q",
    name: "少年得到",
    description: "",
    children: [
      {
        id: "LWYS1K2O3M41V",
        name: "表达素养课",
        description: "",
        children: [],
        modificationTime: 1717407432672,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWYS11CEHU1AN",
        name: "书房已购",
        description: "",
        children: [],
        modificationTime: 1717407408398,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWYS04ITQGA2B",
        name: "我的",
        description: "",
        children: [],
        modificationTime: 1717407365861,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWYRZZEF1VY76",
        name: "阅读课",
        description: "",
        children: [],
        modificationTime: 1717407359223,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWYS0ADI25FSQ",
        name: "首单特惠",
        description: "",
        children: [],
        modificationTime: 1717407373446,
        tags: [],
        password: "",
        passwordTips: "",
      },
    ],
    modificationTime: 1716344757736,
    tags: ["少年得到"],
    password: "",
    passwordTips: "",
    orderBy: "NAME",
    sortIncrease: true,
  },
  {
    id: "LWZSUGVRL5DDJ",
    name: "开言英语",
    description: "",
    children: [],
    modificationTime: 1717469247735,
    tags: [],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWZSVORITCCPN",
    name: "流利说",
    description: "",
    children: [],
    modificationTime: 1717469304606,
    tags: [],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWYSHU1FZXFRR",
    name: "斑马",
    description: "",
    children: [],
    modificationTime: 1717408192083,
    tags: [],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWG8RKGHQY1V0",
    name: "喜马拉雅儿童",
    description: "",
    children: [],
    modificationTime: 1716286662737,
    tags: ["喜马拉雅儿童"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWZSXFOJTAYC6",
    name: "叽里呱啦",
    description: "",
    children: [],
    modificationTime: 1717469386147,
    tags: [],
    password: "",
    passwordTips: "",
    orderBy: "NAME",
    sortIncrease: true,
  },
  {
    id: "LWZSY9RMD1FMG",
    name: "学而思",
    description: "",
    children: [],
    modificationTime: 1717469425138,
    tags: [],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWEQYJ8E3RSTD",
    name: "叫叫",
    description: "",
    children: [
      {
        id: "LWR5X8ZG1DJV7",
        name: "官网",
        description: "",
        children: [
          {
            id: "LX2M3H05FLQW0",
            name: "官网子文件夹",
            description: "",
            children: [],
            modificationTime: 1717639309013,
            tags: [],
            password: "",
            passwordTips: "",
          },
        ],
        modificationTime: 1716947016892,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWOPC806JP99E",
        name: "伴读",
        description: "",
        children: [],
        modificationTime: 1716798229638,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWOPC39MO6VWO",
        name: "学习页",
        description: "",
        children: [],
        modificationTime: 1716798223498,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWOPBBKNESMT5",
        name: "我的",
        description: "",
        children: [],
        modificationTime: 1716798187607,
        tags: [],
        password: "",
        passwordTips: "",
      },
      {
        id: "LWOP9WTOOFD6T",
        name: "广场页",
        description: "",
        children: [],
        modificationTime: 1716798121836,
        tags: [],
        password: "",
        passwordTips: "",
      },
    ],
    modificationTime: 1716196288478,
    tags: ["叫叫"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWOOY0IL7WZ70",
    name: "作业帮",
    description: "",
    children: [],
    modificationTime: 1716797566749,
    tags: ["作业帮"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWOP1M44582U0",
    name: "多领国",
    description: "",
    children: [],
    modificationTime: 1716797734708,
    tags: ["多领国"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWOP09KEMDYF2",
    name: "百词斩",
    description: "",
    children: [],
    modificationTime: 1716797671790,
    tags: ["百词斩"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWOOVX7XAZSIM",
    name: "洋葱学院",
    description: "",
    children: [],
    modificationTime: 1716797469165,
    tags: ["洋葱学院"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWORZ102O0UFV",
    name: "KaDa阅读",
    description: "",
    children: [],
    modificationTime: 1716802652882,
    tags: ["KaDa阅读"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWOSBZ4DU0BNB",
    name: "ahakid",
    description: "",
    children: [],
    modificationTime: 1716803256973,
    tags: ["ahakid"],
    password: "",
    passwordTips: "",
  },
  {
    id: "LWOT3F37WJW4L",
    name: "洪恩分级阅读",
    description: "",
    children: [],
    modificationTime: 1716804537379,
    tags: ["洪恩分级阅读"],
    password: "",
    passwordTips: "",
  },
];
